name: Build 

on: 
  workflow_dispatch: 
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and test
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: show current version of Xcode
        run: xcodebuild -version
